import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LenisProvider from "@/components/LenisProvider";
import { SpeedInsights } from "@vercel/speed-insights/next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ backgroundColor: "#010510" }}>
      <head>
        {/* Evita flash branco nos navegadores: define tema escuro desde o primeiro paint */}
        <meta name="color-scheme" content="dark" />
        <meta name="theme-color" content="#010510" />
        {/* Preload do primeiro frame da sequência de scroll (PNG) — usa CDN se definido */}
        {(() => {
          // Se houver CDN específico para os frames, priorize-o; caso contrário, use NEXT_PUBLIC_CDN_BASE.
          const cdnScroll = process.env.NEXT_PUBLIC_CDN_BASE_SCROLL || process.env.NEXT_PUBLIC_CDN_BASE || "";
          const baseDir = cdnScroll ? `${cdnScroll.replace(/\/$/, "")}/AnimationHero/seq-scroll` : "/AnimationHero/seq-scroll";
          // Nome correto dos frames da sequência (HERO_QUEDA###.png)
          const url = `${baseDir}/HERO_QUEDA001.png`;
          return <link rel="preload" as="image" href={url} type="image/png" />;
        })()}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ backgroundColor: "#010510", color: "#ededed" }}
      >
        <LenisProvider>
          {children}
        </LenisProvider>
        {/* Coleta métricas de desempenho em produção (Vercel Speed Insights) */}
        <SpeedInsights />
      </body>
    </html>
  );
}
